# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [5]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

In [6]:
filtered_customers = df[
    (df["Total Claim Amount"] < 1000) &
    (df["Response"] == "Yes")
]

filtered_customers.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [7]:
filtered_customers.shape

(1399, 26)

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [8]:
yes_customers = df[df["Response"] == "Yes"]

In [9]:
premium_analysis = yes_customers.groupby(
    ["Policy Type", "Gender"]
)["Monthly Premium Auto"].mean()

premium_analysis

Policy Type     Gender
Corporate Auto  F         94.301775
                M         92.188312
Personal Auto   F         98.998148
                M         91.085821
Special Auto    F         92.314286
                M         86.343750
Name: Monthly Premium Auto, dtype: float64

In [10]:
clv_analysis = yes_customers.groupby(
    ["Policy Type", "Gender"]
)["Customer Lifetime Value"].mean()

clv_analysis

Policy Type     Gender
Corporate Auto  F         7712.628736
                M         7944.465414
Personal Auto   F         8339.791842
                M         7448.383281
Special Auto    F         7691.584111
                M         8247.088702
Name: Customer Lifetime Value, dtype: float64

In [11]:
claim_analysis = yes_customers.groupby(
    ["Policy Type", "Gender"]
)["Total Claim Amount"].mean()

claim_analysis

Policy Type     Gender
Corporate Auto  F         433.738499
                M         408.582459
Personal Auto   F         452.965929
                M         457.010178
Special Auto    F         453.280164
                M         429.527942
Name: Total Claim Amount, dtype: float64

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [12]:
customers_by_state = df.groupby("State")["Customer"].count()

customers_by_state

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

In [13]:
customers_by_state_filtered = customers_by_state[customers_by_state > 500]

customers_by_state_filtered

State
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: Customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [14]:
clv_stats = df.groupby(
    ["Education", "Gender"]
)["Customer Lifetime Value"].agg(["max", "min", "median"])

clv_stats

                                     max          min       median
Education            Gender
Bachelor             F       73225.95652  1904.000852  5640.505303
                     M       67907.27050  1898.007675  5548.031892
College              F       61850.18803  1898.683686  5623.611187
                     M       61134.68307  1918.119700  6005.847375
Doctor               F       44856.11397  2395.570000  5332.462694
                     M       32677.34284  2267.604038  5577.669457
High School or Below F       55277.44589  2144.921535  6039.553187
                     M       83325.38119  1940.981221  6286.731006
Master               F       51016.06704  2417.777032  5729.855012
                     M       50568.25912  2272.307310  5579.099207

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [15]:
df["Effective To Date"] = pd.to_datetime(df["Effective To Date"])
df["Month"] = df["Effective To Date"].dt.month

/var/folders/0_/937qdrnn19vgx61scsk5r5j40000gn/T/ipykernel_87554/1172233720.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Effective To Date"] = pd.to_datetime(df["Effective To Date"])

In [16]:
policies_by_state_month = df.groupby(
    ["State", "Month"]
)["Policy"].count().reset_index()

In [17]:
pivot_table = policies_by_state_month.pivot(
    index="State",
    columns="Month",
    values="Policy"
)

pivot_table

Month          1     2
State
Arizona     1008   929
California  1918  1634
Nevada       551   442
Oregon      1565  1344
Washington   463   425

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [18]:
top_states = df.groupby("State")["Policy"].count().sort_values(ascending=False).head(3)

top_states

State
California    3552
Oregon        2909
Arizona       1937
Name: Policy, dtype: int64

In [19]:
top_states_list = top_states.index.tolist()

top_states_data = df[df["State"].isin(top_states_list)]

In [20]:
top_states_table = top_states_data.pivot_table(
    index="State",
    columns="Month",
    values="Policy",
    aggfunc="count"
)

top_states_table

Month          1     2
State
Arizona     1008   929
California  1918  1634
Oregon      1565  1344

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

In [21]:
df["Response Binary"] = df["Response"].map({"Yes": 1, "No": 0})

In [22]:
response_rate = df.groupby("Sales Channel")["Response Binary"].mean()

response_rate

Sales Channel
Agent          0.190746
Branch         0.113787
Call Center    0.109786
Web            0.117141
Name: Response Binary, dtype: float64

In [23]:
response_table = df.pivot_table(
    values="Response Binary",
    index="Sales Channel",
    aggfunc="mean"
)

response_table

               Response Binary
Sales Channel
Agent                 0.190746
Branch                0.113787
Call Center           0.109786
Web                   0.117141

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9